### ISSUE TITLE
Some suggestions for a more approachable code

### ISSUE THREAD

**Issue by mancellin** [dNamiLab/dNami#19]
Below are some comments I collected when going through the `genRhs.py` and `genKer.py` files. Most of them are very subjective, so take them as suggestions and not as requirements for publication of the [JOSS paper](https://github.com/openjournals/joss-reviews/issues/4186).

* To make the code more approachable by new users and developers, I suggest following the standard typographic convention of writing names of:
  * modules, functions and variables in snake_case,
  * classes in CamelCase,
  * global constants in CAPITALS.

* There are two different things called respectively `rhsinfo` and `rhs_info`. Maybe you could give them distinct names. For instance `Parameters` and `export_parameters`.

* In `rhs_info` in `genKer.py`, you import from `genRhs.py` some variables that were actually defined in `rhs.py`. Why not directly read `rhs.py`?
  More generally, you call in `genRhs.py` functions defined in `genKer.py` that import variables from `genRhs.py`. In my opinion, you are risking making your library an unmaintainable entangled mess, which could easily be avoided by passing variables (such as `incPath`) as function arguments.

* In many functions in `genKer.py`, `rhs` is an optional argument (with default value `None`). But the functions cannot succeed if `rhs` is not provided, so why not making it a mandatory argument and have more explicit error messages?

* I don't really understand the purpose of `Save_eqns`. Are the `append_Rhs` functions supposed to modify their first argument?

**Comment by etouber** [comment]
Hi @mancellin, thank you for the suggestions. Regarding your first point, this task requires some significant work to unify the code and risks breaking some functionalities in the short-run. We have a few additional test cases in mind we would like to prepare with the current version that would then be used to validate a reformatting down the line. 

Regarding your other points:

    - rhs.py is now called equations.py in the documentation and the examples. Note that this file is not mandatory to the dNami framework. The only requirement is that dictionaries of equations are seen at the genRhs.py level (part of the framework).

    - we have added an ``export`` method to the rhs class to remove the confusion between rhsinfo and rhs_info

    - all imports from genRhs.py are now performed once when instantiating the rhs_info class. Explicit error messages are added when rhs_info is not instantiated before a call to append_Rhs or genBC to reflect anything the user might have missed. This should streamline the 'genRhs.py' file. For example, the user no longer needs to carry out the 'Save_eqns' step with these modifications, as you pointed out.  

Thank you for helping us improve dNami!

**Comment by mancellin** [comment]
Thank you for taking my suggestions into account! The code seems already clearer to me.

If you don't mind, I'd like to suggest you to go one step further: remove the import statements in `rhs_info` and pass explicitly the parameters, as in
```python
rhs = rhs_info(varname=varname, varsolved=varsolved,
               hlo_glob=6, dim=1, wp='float64', incPATH='...')
```
It is a bit more verbose, but I believe it is worth it:
* it is more explicit and users know where each parameter is required (e.g. it is currently hard to guess that `wp` should be defined *before* calling `rhs_info()`).
* it should work even if `genRhs.py` is not named `genRhs`, and even if it is not in the same directory as `genKer.py` (as long as `genKer.py` is in the PYTHONPATH),
* you could then be a few small steps away from removing the requirement of manually copying files in `generate/` in dNami source tree, making dNami less cumbersome for users and for testing.
