### ISSUE TITLE
Quoting in shell scripts

### ISSUE THREAD

**Issue by mancellin** [dNamiLab/dNami#21]
[I believe it is recommended](https://stackoverflow.com/questions/33318499/should-i-use-quotes-in-environment-path-names) to wrap shell variables in quotes when writing shell scripts.
That is for instance, using
```
export  PYTHONPATH="$PYTHONPATH:$INSTALLPATH/src_py"
```
instead of
```
export  PYTHONPATH=$PYTHONPATH:$INSTALLPATH/src_py
```

On most shell, it is safer in case there is a space in a file or directory name.
On the [fish shell](https://fishshell.com/), only the former is working.

**Comment by etouber** [comment]
Hi @mancellin, thank you for this, we've update the ``env_dNami.sh`` file to reflect this.
